stages:
  - test
  - package

variables:
  NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget/packages

cache:
  key: ${CI_COMMIT_REF_SLUG}-nuget
  paths:
    - .nuget/packages

cache:
  key: ${CI_COMMIT_REF_SLUG}-nuget
  paths:
    - .nuget/packages

test:
  image: mcr.microsoft.com/dotnet/sdk:10.0
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - dotnet restore
    - dotnet build PanicEngine.sln --configuration Release --no-restore
    - dotnet test PanicEngine.sln --configuration Release --no-build --verbosity normal

publish:
  image: mcr.microsoft.com/dotnet/sdk:10.0
  stage: publish
  script:
    - dotnet pack src/PanicEngine/PanicEngine.csproj -c Release -o out
    - dotnet nuget add source "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/nuget/index.json"
      --name gitlab-panicengine
      --username gitlab-ci-token
      --password $CI_JOB_TOKEN
      --store-password-in-clear-text
    - dotnet nuget push "out/*.nupkg" --source gitlab-panicengine --api-key $CI_JOB_TOKEN --skip-duplicate