stages:
  - test

variables:
  NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget/packages

cache:
  key: ${CI_COMMIT_REF_SLUG}-nuget
  paths:
    - .nuget/packages

test:
  image: mcr.microsoft.com/dotnet/sdk:10.0
  stage: test
  script:
    - dotnet restore
    - dotnet build PanicEngine.sln --configuration Release --no-restore
    - dotnet test PanicEngine.sln --configuration Release --no-build --verbosity normal